#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Bitcoin Knowledge Podcast

# Short bio or description (displayed in the header)
description: Interviews with the top people in the Bitcoin world.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /bitcoinkn/images/bitcoin-knowledge-podcast-avatar.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: bitcoinknowledge
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: bitcoinkn
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: runtogoldtv

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-144215-15

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://www.bitcoin.kn

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "http://sunnankar.github.io/bitcoinkn"


# Podcast General Settings
# ------------------------------------------------------------------------

# The homepage of your podcast
podcastSite: http://www.bitcoin.kn

# The cover image for the podcast, will show in search results in iTunes
podcastCoverImg: bitcoinkn/images/bitcoin-knowledge-podcast-1600.jpg

# The name of your podcast
podcastTitle: Bitcoin Knowledge Podcast

# About You. For iTunes admin. This information is not displayed on the iTunes Store.
podcastOwner: Trace Mayer, J.D.
podcastEmail: podcast@trace-mayer.com

# See https://www.apple.com/itunes/podcasts/specs.html near the bottom for valid categories
category: Education
subCategory: Higher Education

# is it too dangerous for the impressionable kiddos?
podcastIsExplicit: "clean"


podcastAuthor: Trace Mayer, J.D.
podcastDescription: Interviews with the top people in the Bitcoin world. Your host is Trace Mayer, J.D. recommended Bitcoin around a nickel and has invested in key infrastructure such as Armory - the most secure Bitcoin wallet, Bitpay - the largest Bitcoin merchant processor, Kraken - the largest Euro and best Bitcoin exchange, Netagio - a custody business and Bitcoin Magazine where he is on the Editorial Board. He has helped many people profit by demonstrating a significant documented foresight and prognostication ability in the money, currency and payment markets and developments. Gold, Bitcoin, silver, finance and economics. Monetary science applied to current events. This wrapup will teach you about sound money and cutting edge technologies to help you protect, preserve and grow your wealth during The Great Credit Contraction holders of capital are increasingly seeking safety and liquidity. Mr. Mayer has earned degrees in accounting and law and has studied the Austrian school of economics. He has authored several books including The Great Credit Contraction and How To Vanish, operates two popular blogs RunToGold and HowToVanish, speaks internationally at investment conferences like the industry leading Cambridge House and is involved in many entrepreneurial ventures. Gold has been the penultimate safe haven throughout millennia and will remain the Ancient Metal of Kings. But the new decentralized peer-to-peer censorship-resistant cryptocurrency Bitcoin has set a new standard for liquidity. Bitcoin allow users to send any amount of money to any other person instantly without a fee to anywhere in the world without any restrictions whatsoever. Because bitcoins are a sterile asset, like gold, any rise in price functions as a wealth transfer from other assets in the economy to holders of bitcoins. For the past decade the fiat currency collapse has continued unabated with all major fiat currencies falling relative to gold. But at the same time over the past couple years gold has completely collapsed relative to Bitcoin; gold’s performance relative to Bitcoin is worse than the Argentina Peso against the USD. The market has a way of financially rewarding the solutions, instead of refuges, because they add more value to society. And that is what gold’s currency collapse relative to Bitcoin is signaling; a massive wealth transfer has started from holders of assets in the traditional fiat currency system, gold, silver, etc. and other assets to holders of bitcoins.

podcastSubtitle: Interviews with the top people in the Bitcoin world.



#                          ###



# Don't edit below this line unless you know what you are doing.
# ------------------------------------------------------------------------


# Create a Jekyll collection to handle the episodes
collections:
- episodes

# Identify a place to output the generated files
destination: _upload-this

# Keep the readme out of the output folder
exclude: ['readme.md']


#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
